### PR TITLE
User scripts e2e testing

### LINKED ISSUE #136: Add basic e2e tests for user scripts
Like we have for workspace scripts. I noticed while adding JS scripts support that it is entirely possible to make things work for workspace scripts, and fail for user scripts. 😄

### LINKED ISSUE #138: Ensure that Joyride's `cljs.test` actually runs tests
From @borkdude on Slack:

> One potential issue: how do we know for sure that the SCI cljs.test version works and doesn't accidentally mark everything as succesful or forgets to run certain tests? :)

### LINKED ISSUE #139: Default user content places `my_lib.cljs` in `scripts` folder, should be in `src` folder
When adding `src` to the classpath we missed to also make the default getting-started user content utilize this for moving `my_lib.cljs` out of the `scripts` folder. So now it keeps littering down the User scripts menu, for old and new users alike.

### PR DESCRIPTION
**Pull request by PEZ**
Changes:

* Add configurable user scripts location via env var
* Add smoke test for user-activate
* Add JS example script to default user scripts content
* Always reload JS user scripts when they are run (a bug I found when testing the user scripts)
* Add check for minimum assertions passed
* Create user getting-started `my_lib.cljs` in `src`
* Only create getting-started user content if activate script is missing

Issues addressed:

* Fixes #136
* Fixes #138
* Fixes #139

TODO:

* [x] Add more smoke tests
* [x] Handle new my-lib location somehow
* [x] Figure out how to test that JS scripts are reloaded

### CODE REVIEW

**Comment by PEZ** [comment]
> * Figure out how to test that JS scripts are reloaded

@borkdude I changed so that when JS scripts are run, they are reloaded. A plain `(js/require ...)` doesn't do this, it will returned the cached module on subsequent requires of the same script. I'd like to have a test that confirms this reload functionality. Do you have any idea how to go about with this? I could create a file and have update a counter in it, but maybe there is an easier way...

**Comment by borkdude** [comment]
I guess you could make a change in the script as part of the test and then you should expect a different output on the second run?

**Comment by PEZ** [comment]
Ah, yeah, I'll do it that way!

**Comment by PEZ** [comment]
Now there's a test for the reloading behaviour of JS scripts.

**Comment by borkdude** [comment]
LGTM so far (still draft?)

**Comment by PEZ** [comment]
Thanks for reviewing! Yes, still in draft to protect from me hitting the wrong button while I figure out how to deal with the fact that this PR currently makes many existing users have two `my_lib.cljs` in the User content. Because the PR, in its current state, installs a `my_lib.cljs` to `<user-config>/joyride/src/`, if it isn't present there already.

The `my_lib.cljs` originally, and currently, was/is installed to `scripts/`, while now that we have `src/` in the classpath it makes much more sense to put it there.  I want it to be moved there for existing users, but I don't know if that could be disruptive. A case where it would break things if is someone has started using JS local file requires from this script. I think it could be tricky to spot this situation, which also probably is non-existing out there.

If I don't come up with something quickly, I'll remove this change from the PR, but it still needs a solution, because it's a bad pattern to have this example content in the `scripts` directory.

**Comment by PEZ** [comment]
For now I decided to change the creation of user getting-started content such that it only happens if the `user_activate.cljs` file is missing. This way we won't create a new `my_lib.cljs` for existing users (who will always have this activation script, because we always create it, if it is missing).

And then we can figure later on whether we want to help existing users get aware of the misplacement of `my_lib.cljs`.

**Pull request merged**
