### PR TITLE
WIP: Use latest sci.configs

### PR DESCRIPTION
**Pull request by PEZ**
Trying to get at `p/handle` et al, which were added in a more recent sci.configs.

However, right now not getting it to work, even though it works if I use `:local/deps`

Seeing the same in `nbb`, I think:

```
% npx nbb -e "(require 'promesa.core) promesa.core/handle"
Need to install the following packages:
  nbb
Ok to proceed? (y) 
----- Error --------------------------------------
Message:  Could not resolve symbol: promesa.core/handle
Location: 1:25
Phase:    analysis
Could not resolve symbol: promesa.core/handle
```

UPDATE: That was not so, `npx` seems to give me some old version:

```
npx nbb --version                                       
Need to install the following packages:
  nbb
Ok to proceed? (y) 
----- Error --------------------------------------
Message:  ENOENT: no such file or directory, open '/Users/pez/Projects/joyride/--version'
ENOENT: no such file or directory, open '/Users/pez/Projects/joyride/--version'
~/Projects/joyride(pez/bump-sci-configs-dep|✔) % nbb --version
zsh: command not found: nbb
~/Projects/joyride(pez/bump-sci-configs-dep|✔) % npm install -g nbb

added 6 packages, and audited 7 packages in 3s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
~/Projects/joyride(pez/bump-sci-configs-dep|✔) % nbb --version     
nbb v0.5.103
~/Projects/joyride(pez/bump-sci-configs-dep|✔) % nbb -e "(require 'promesa.core) promesa.core/handle" 
#object[n$]
```

So it totally works with latest nbb.

### CODE REVIEW

**Comment by PEZ** [comment]
Right now I can't get it to work with `:local/root` either, so this must be a caching issue.

**Comment by borkdude** [comment]
Nbb issue is something weird with npx. `npx nbb@latest` works.

I have no issue building the PR here and using `p/handle` when evaluating code.

Screenshot 2022-05-18 at 10 14 49

**Comment by PEZ** [comment]
That works for me too...

I think I might have been committing the noob Calva user mistake to not load the file before I evaluated my test code, which was in a rich comment...

**Comment by PEZ** [comment]
This is ready for your review now, @borkdude 🙏

**Comment by borkdude** [comment]
Ship it.

**Pull request merged**
