### PR TITLE
Add kaocha runner and files for testing

### PR DESCRIPTION
**Pull request by erickisos**

### CODE REVIEW

**Comment by borkdude** [comment]
I think we could close this now, @PEZ

**Comment by borkdude** [comment]
Thank you for your PR. We've decided on a different direction for tests.

**Comment by PEZ** [comment]
@erickisos, many thanks for this suggestion! 🙏  We decided to go with an end-to-end testing strategy for starters, built with Joyride itself. We have some basic tests in place now. Please feel invited to suggest and contribute testing coverage.

**Comment by erickisos** [comment]
Thanks folks, I will check that! 💜

**Pull request closed without merging**
